export const livrosIniciais = [
  // LITERATURA BRASILEIRA
  {
    id: 'livro-1',
    titulo: 'Dom Casmurro',
    autor: 'Machado de Assis',
    pais: 'Brasil',
    genero: 'Romance',
    ano: 1899,
    sinopse: 'Bentinho narra sua vida, o amor por Capitu e a dúvida que jamais o abandona sobre a suposta traição.',
    capa: '📖',
    exemplares: 3,
  },
  {
    id: 'livro-2',
    titulo: 'Memórias Póstumas de Brás Cubas',
    autor: 'Machado de Assis',
    pais: 'Brasil',
    genero: 'Romance',
    ano: 1881,
    sinopse: 'Um defunto-autor narra sua própria vida com ironia e pessimismo, inaugurando o Realismo brasileiro.',
    capa: '📚',
    exemplares: 2,
  },
  {
    id: 'livro-3',
    titulo: 'Grande Sertão: Veredas',
    autor: 'João Guimarães Rosa',
    pais: 'Brasil',
    genero: 'Romance',
    ano: 1956,
    sinopse: 'O jagunço Riobaldo narra sua vida pelo sertão mineiro e o possível pacto com o diabo.',
    capa: '📖',
    exemplares: 2,
  },
  {
    id: 'livro-4',
    titulo: 'O Cortiço',
    autor: 'Aluísio Azevedo',
    pais: 'Brasil',
    genero: 'Naturalismo',
    ano: 1890,
    sinopse: 'A vida coletiva e degradante num cortiço carioca do século XIX, reflexo das tensões sociais.',
    capa: '🏚️',
    exemplares: 2,
  },
  {
    id: 'livro-5',
    titulo: 'Iracema',
    autor: 'José de Alencar',
    pais: 'Brasil',
    genero: 'Romance',
    ano: 1865,
    sinopse: 'A lenda do Ceará e o amor trágico entre a índia Iracema e o guerreiro Martim.',
    capa: '🌿',
    exemplares: 3,
  },
  {
    id: 'livro-6',
    titulo: 'Vidas Secas',
    autor: 'Graciliano Ramos',
    pais: 'Brasil',
    genero: 'Romance',
    ano: 1938,
    sinopse: 'A saga de Fabiano e sua família retirante pelo sertão nordestino numa luta pela sobrevivência.',
    capa: '🌵',
    exemplares: 3,
  },
  {
    id: 'livro-7',
    titulo: 'Macunaíma',
    autor: 'Mário de Andrade',
    pais: 'Brasil',
    genero: 'Modernismo',
    ano: 1928,
    sinopse: 'O herói sem nenhum caráter percorre o Brasil numa jornada mítica e satírica da identidade nacional.',
    capa: '🦜',
    exemplares: 2,
  },
  {
    id: 'livro-8',
    titulo: 'São Bernardo',
    autor: 'Graciliano Ramos',
    pais: 'Brasil',
    genero: 'Romance',
    ano: 1934,
    sinopse: 'Paulo Honório narra sua ascensão social e sua relação destrutiva com Madalena, a esposa que ele amava e destruiu.',
    capa: '📖',
    exemplares: 2,
  },
  {
    id: 'livro-9',
    titulo: 'Capitães da Areia',
    autor: 'Jorge Amado',
    pais: 'Brasil',
    genero: 'Romance',
    ano: 1937,
    sinopse: 'O grupo de meninos abandonados que vivia nas ruas de Salvador, sua luta pela sobrevivência e seus sonhos.',
    capa: '🌊',
    exemplares: 3,
  },
  {
    id: 'livro-10',
    titulo: 'A Moreninha',
    autor: 'Joaquim Manuel de Macedo',
    pais: 'Brasil',
    genero: 'Romance',
    ano: 1844,
    sinopse: 'Considerado o primeiro romance brasileiro, narra o amor entre estudantes numa ilha perto do Rio.',
    capa: '💛',
    exemplares: 2,
  },

  // LITERATURA MUNDIAL — PORTUGAL
  {
    id: 'livro-11',
    titulo: 'Os Lusíadas',
    autor: 'Luís de Camões',
    pais: 'Portugal',
    genero: 'Poesia Épica',
    ano: 1572,
    sinopse: 'Épico que celebra a viagem de Vasco da Gama às Índias e os grandes feitos dos portugueses.',
    capa: '⚓',
    exemplares: 2,
  },
  {
    id: 'livro-12',
    titulo: 'O Crime do Padre Amaro',
    autor: 'Eça de Queirós',
    pais: 'Portugal',
    genero: 'Romance',
    ano: 1875,
    sinopse: 'A hipocrisia do clero português e o amor proibido entre um padre e uma jovem devota.',
    capa: '⛪',
    exemplares: 2,
  },

  // LITERATURA MUNDIAL — RÚSSIA
  {
    id: 'livro-13',
    titulo: 'Crime e Castigo',
    autor: 'Fiódor Dostoiévski',
    pais: 'Rússia',
    genero: 'Romance',
    ano: 1866,
    sinopse: 'Raskólnikov comete um assassinato acreditando-se acima da moral comum e enfrenta as consequências psicológicas.',
    capa: '🔪',
    exemplares: 3,
  },
  {
    id: 'livro-14',
    titulo: 'Guerra e Paz',
    autor: 'Liev Tolstói',
    pais: 'Rússia',
    genero: 'Romance',
    ano: 1869,
    sinopse: 'A Rússia napoleônica vista através de famílias aristocráticas numa das maiores obras da literatura universal.',
    capa: '⚔️',
    exemplares: 2,
  },
  {
    id: 'livro-15',
    titulo: 'Anna Kariênina',
    autor: 'Liev Tolstói',
    pais: 'Rússia',
    genero: 'Romance',
    ano: 1878,
    sinopse: 'A trágica história de amor de Anna, presa entre o dever social e a paixão avassaladora.',
    capa: '🌹',
    exemplares: 2,
  },
  {
    id: 'livro-16',
    titulo: 'O Idiota',
    autor: 'Fiódor Dostoiévski',
    pais: 'Rússia',
    genero: 'Romance',
    ano: 1869,
    sinopse: 'O príncipe Míchkin, puro e ingênuo, mergulha na sociedade corrupta de São Petersburgo.',
    capa: '📖',
    exemplares: 2,
  },

  // LITERATURA MUNDIAL — FRANCE
  {
    id: 'livro-17',
    titulo: 'Os Miseráveis',
    autor: 'Victor Hugo',
    pais: 'França',
    genero: 'Romance',
    ano: 1862,
    sinopse: 'Jean Valjean, ex-presidiário, busca redenção numa França marcada pela injustiça social.',
    capa: '🕯️',
    exemplares: 3,
  },
  {
    id: 'livro-18',
    titulo: 'Madame Bovary',
    autor: 'Gustave Flaubert',
    pais: 'França',
    genero: 'Romance',
    ano: 1857,
    sinopse: 'Emma Bovary busca escapar da mediocridade provincial através de amores adúlteros e fantasias românticas.',
    capa: '🌸',
    exemplares: 2,
  },
  {
    id: 'livro-19',
    titulo: 'O Conde de Monte Cristo',
    autor: 'Alexandre Dumas',
    pais: 'França',
    genero: 'Aventura',
    ano: 1844,
    sinopse: 'Edmond Dantès é preso injustamente e planeja uma vingança meticulosa após encontrar um tesouro.',
    capa: '💎',
    exemplares: 3,
  },
  {
    id: 'livro-20',
    titulo: 'Em Busca do Tempo Perdido',
    autor: 'Marcel Proust',
    pais: 'França',
    genero: 'Romance',
    ano: 1913,
    sinopse: 'Uma das maiores obras da literatura, mergulha na memória, tempo e experiência subjetiva da Belle Époque.',
    capa: '🌺',
    exemplares: 1,
  },

  // LITERATURA MUNDIAL — REINO UNIDO
  {
    id: 'livro-21',
    titulo: 'Dom Quixote',
    autor: 'Miguel de Cervantes',
    pais: 'Espanha',
    genero: 'Romance',
    ano: 1605,
    sinopse: 'O cavaleiro andante que confunde a realidade com a ficção, acompanhado pelo fiel Sancho Pança.',
    capa: '🏇',
    exemplares: 2,
  },
  {
    id: 'livro-22',
    titulo: 'Hamlet',
    autor: 'William Shakespeare',
    pais: 'Reino Unido',
    genero: 'Teatro',
    ano: 1603,
    sinopse: 'O príncipe Hamlet descobre que seu pai foi assassinado pelo tio e enfrenta dilemas morais e existenciais.',
    capa: '💀',
    exemplares: 3,
  },
  {
    id: 'livro-23',
    titulo: 'Orgulho e Preconceito',
    autor: 'Jane Austen',
    pais: 'Reino Unido',
    genero: 'Romance',
    ano: 1813,
    sinopse: 'Elizabeth Bennet e Mr. Darcy superam seus preconceitos para encontrar o amor verdadeiro.',
    capa: '🎀',
    exemplares: 3,
  },
  {
    id: 'livro-24',
    titulo: '1984',
    autor: 'George Orwell',
    pais: 'Reino Unido',
    genero: 'Distopia',
    ano: 1949,
    sinopse: 'Em um regime totalitário opressivo, Winston Smith questiona o sistema e busca a liberdade.',
    capa: '👁️',
    exemplares: 3,
  },
  {
    id: 'livro-25',
    titulo: 'Admirável Mundo Novo',
    autor: 'Aldous Huxley',
    pais: 'Reino Unido',
    genero: 'Distopia',
    ano: 1932,
    sinopse: 'Uma sociedade futurista onde a felicidade é controlada e a individualidade suprimida.',
    capa: '🧬',
    exemplares: 2,
  },

  // LITERATURA MUNDIAL — ALEMANHA / ÁUSTRIA
  {
    id: 'livro-26',
    titulo: 'Fausto',
    autor: 'Johann Wolfgang von Goethe',
    pais: 'Alemanha',
    genero: 'Teatro',
    ano: 1808,
    sinopse: 'O doutor Fausto vende sua alma ao diabo Mefistófeles em troca de conhecimento e prazer.',
    capa: '🔥',
    exemplares: 2,
  },
  {
    id: 'livro-27',
    titulo: 'A Metamorfose',
    autor: 'Franz Kafka',
    pais: 'República Tcheca',
    genero: 'Conto',
    ano: 1915,
    sinopse: 'Gregor Samsa acorda transformado em um inseto gigante e observa o desmoronamento das relações familiares.',
    capa: '🪲',
    exemplares: 3,
  },

  // LITERATURA MUNDIAL — EUA
  {
    id: 'livro-28',
    titulo: 'O Velho e o Mar',
    autor: 'Ernest Hemingway',
    pais: 'Estados Unidos',
    genero: 'Novela',
    ano: 1952,
    sinopse: 'Santiago, um velho pescador, trava uma batalha épica e solitária com um enorme marlim no Golfo.',
    capa: '🎣',
    exemplares: 3,
  },
  {
    id: 'livro-29',
    titulo: 'Moby Dick',
    autor: 'Herman Melville',
    pais: 'Estados Unidos',
    genero: 'Aventura',
    ano: 1851,
    sinopse: 'O Capitão Ahab conduz sua tripulação numa obsessiva caça à baleia branca que lhe arrancou a perna.',
    capa: '🐋',
    exemplares: 2,
  },
  {
    id: 'livro-30',
    titulo: 'As Aventuras de Tom Sawyer',
    autor: 'Mark Twain',
    pais: 'Estados Unidos',
    genero: 'Aventura',
    ano: 1876,
    sinopse: 'Tom Sawyer vive aventuras na beira do rio Mississippi, testemunha um assassinato e encontra um tesouro.',
    capa: '🏄',
    exemplares: 3,
  },

  // LITERATURA MUNDIAL — COLOMBIA/AMERICA LATINA
  {
    id: 'livro-31',
    titulo: 'Cem Anos de Solidão',
    autor: 'Gabriel García Márquez',
    pais: 'Colômbia',
    genero: 'Realismo Mágico',
    ano: 1967,
    sinopse: 'A saga da família Buendía e a cidade de Macondo ao longo de um século de história e magia.',
    capa: '🦋',
    exemplares: 3,
  },
  {
    id: 'livro-32',
    titulo: 'O Amor nos Tempos do Cólera',
    autor: 'Gabriel García Márquez',
    pais: 'Colômbia',
    genero: 'Romance',
    ano: 1985,
    sinopse: 'Florentino Ariza espera mais de cinquenta anos pelo amor de Fermina Daza, recusando-se a desistir.',
    capa: '💌',
    exemplares: 2,
  },

  // LITERATURA MUNDIAL — ITALIA
  {
    id: 'livro-33',
    titulo: 'A Divina Comédia',
    autor: 'Dante Alighieri',
    pais: 'Itália',
    genero: 'Poesia Épica',
    ano: 1320,
    sinopse: 'Dante percorre o Inferno, o Purgatório e o Paraíso guiado por Virgílio numa viagem pela eternidade.',
    capa: '🔱',
    exemplares: 2,
  },
  {
    id: 'livro-34',
    titulo: 'O Nome da Rosa',
    autor: 'Umberto Eco',
    pais: 'Itália',
    genero: 'Mistério',
    ano: 1980,
    sinopse: 'O frade Guilherme de Baskerville investiga mortes misteriosas num mosteiro medieval italiano.',
    capa: '🌹',
    exemplares: 2,
  },

  // LITERATURA MUNDIAL — JAPÃO
  {
    id: 'livro-35',
    titulo: 'O Som das Ondas',
    autor: 'Yukio Mishima',
    pais: 'Japão',
    genero: 'Romance',
    ano: 1954,
    sinopse: 'A história de amor simples e puro entre dois jovens numa pequena ilha de pescadores japonesa.',
    capa: '🌊',
    exemplares: 2,
  },
  {
    id: 'livro-36',
    titulo: 'Kokoro',
    autor: 'Natsume Soseki',
    pais: 'Japão',
    genero: 'Romance',
    ano: 1914,
    sinopse: 'Uma reflexão profunda sobre solidão, culpa e amizade no Japão da era Meiji.',
    capa: '🗾',
    exemplares: 2,
  },

  // LITERATURA MUNDIAL — GRÉCIA ANTIGA / CLÁSSICOS
  {
    id: 'livro-37',
    titulo: 'Ilíada',
    autor: 'Homero',
    pais: 'Grécia',
    genero: 'Poesia Épica',
    ano: -800,
    sinopse: 'A guerra de Troia e a ira do herói Aquiles, um dos mais antigos e influentes poemas do mundo.',
    capa: '⚔️',
    exemplares: 2,
  },
  {
    id: 'livro-38',
    titulo: 'Odisseia',
    autor: 'Homero',
    pais: 'Grécia',
    genero: 'Poesia Épica',
    ano: -800,
    sinopse: 'A longa jornada do astuto Odisseu para retornar a Ítaca após a queda de Troia.',
    capa: '🌊',
    exemplares: 2,
  },

  // LITERATURA MUNDIAL — NORUEGA
  {
    id: 'livro-39',
    titulo: 'Pan',
    autor: 'Knut Hamsun',
    pais: 'Noruega',
    genero: 'Romance',
    ano: 1894,
    sinopse: 'O tenente Thomas Glahn vive sozinho na floresta norueguesa e se apaixona por uma mulher livre e enigmática.',
    capa: '🌲',
    exemplares: 2,
  },

  // LITERATURA MUNDIAL — ARGENTINA
  {
    id: 'livro-40',
    titulo: 'Ficções',
    autor: 'Jorge Luis Borges',
    pais: 'Argentina',
    genero: 'Contos',
    ano: 1944,
    sinopse: 'Labirintos, bibliotecas infinitas, espelhos e o tempo são os personagens destes contos filosóficos e fantásticos.',
    capa: '🔮',
    exemplares: 3,
  },
];

export const generos = [...new Set(livrosIniciais.map(l => l.genero))].sort();
export const paises = [...new Set(livrosIniciais.map(l => l.pais))].sort();
export const autores = [...new Set(livrosIniciais.map(l => l.autor))].sort();